
// This file was auto-generated by ML.NET Model Builder. 

using Underwritting_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
Underwritting.ModelInput sampleData = new Underwritting.ModelInput()
{
    Loan_id = 2F,
    No_of_dependents = 0F,
    Education = @"Not Graduate",
    Income_annum = 4100000F,
    Loan_amount = 1.22E+07F,
    Loan_term = 8F,
    Cibil_score = 417F,
    Residential_assets_value = 2700000F,
    Commercial_assets_value = 2200000F,
    Luxury_assets_value = 8800000F,
    Bank_asset_value = 3300000F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Loan_status with predicted Loan_status from sample data...\n\n");


Console.WriteLine($"Loan_id: {2F}");
Console.WriteLine($"No_of_dependents: {0F}");
Console.WriteLine($"Education: {@"Not Graduate"}");
Console.WriteLine($"Income_annum: {4100000F}");
Console.WriteLine($"Loan_amount: {1.22E+07F}");
Console.WriteLine($"Loan_term: {8F}");
Console.WriteLine($"Cibil_score: {417F}");
Console.WriteLine($"Residential_assets_value: {2700000F}");
Console.WriteLine($"Commercial_assets_value: {2200000F}");
Console.WriteLine($"Luxury_assets_value: {8800000F}");
Console.WriteLine($"Bank_asset_value: {3300000F}");
Console.WriteLine($"Loan_status: {@"Rejected"}");


var sortedScoresWithLabel = Underwritting.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

